fruits = ['grape', 'raspberry', 'apple', 'banna']
print("fruits", fruits, sep='\n')
print("sorted(fruits) ", sorted(fruits), sep='\n')
print("fruits", fruits, sep='\n')
print("sorted(fruits, reverse=True) ", sorted(fruits, reverse=True), sep='\n')
print("sorted(fruits, key=len) ", sorted(fruits, key=len), sep='\n')
print("sorted(fruits, key=len, reverse=True) ", sorted(fruits, key=len, reverse=True), sep='\n')
print("fruits", fruits, sep='\n')
fruits.sort()
print("fruits.sort()", fruits, sep='\n')